# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/init.ipynb (unless otherwise specified).

__all__ = ['is_main', 'start_log']

# Cell
import logging

def is_main(calling_globals):
    #not running in jupyter notebook and is the main function
    return not calling_globals.get('get_ipython', False) and calling_globals['__name__'] == '__main__'

def start_log(logger_name=None):
    '''
    Start a log that displays on stdout
    '''
    logger = logging.getLogger(logger_name)
    screen_handler = logging.StreamHandler()
    formatter = logging.Formatter(
            fmt='[%(levelname)s] %(module)s(%(funcName)s)%(asctime)s--> %(lineno)s.\t %(message)s')
    screen_handler.setFormatter(formatter)
    if not logger.handlers:
        logger.addHandler(screen_handler)
    logger.setLevel(logging.DEBUG)
    return logger