# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/config.ipynb (unless otherwise specified).

__all__ = ['logger', 'config_file']

# Cell
import os
import yaml
import logging
logger = logging.getLogger()

config_file = os.environ.get("SEWING_CONFIG_FILE", 'config.yaml')
logger.info('Config file: {}'.format(config_file))
try:
    with open(config_file) as f:
        configs = yaml.safe_load(f)
except FileNotFoundError:
    configs = {
        'frequency': {'hours': 24},  #how often emails are sent
        'lookback': {'days': 1},  #how far to look back for messages

    }

logger.info('{}'.format(configs))