# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/config.ipynb (unless otherwise specified).

__all__ = ['config_file']

# Cell
import os
import yaml


config_file = os.environ.get("SEWING_CONFIG_FILE", 'config.yaml')

try:
    with open(config_file) as f:
        configs = yaml.safe_load(f)
except FileNotFoundError:
    configs = {
        'frequency': {'hours': 24},  #how often emails are sent
        'send_on_start': False,  #send an email right when the bot starts
        'lookback': {'days': 1},  #how far to look back for messages

    }
