version: "3.7"

networks: 
    network:
        name: "sewing_network"

volumes: 
    neo4j_data: {}

services:
    neo4j:
        image: neo4j:4.3.2
        restart: unless-stopped
        networks:
            - network
        ports:
            - "${neo4j_http_port}:7474"
            - "${neo4j_https_port}:7473"
            - "${neo4j_bolt_port}:7687"
        volumes:
            - ./vendor/neo4j/logs:/logs
            - ./vendor/neo4j/import:/var/lib/neo4j/import
            - ./vendor/neo4j/plugins:/plugins
              #- ./vendor/neo4j/conf:/conf
            - "neo4j_data:/data"
        environment:
            - "NEO4J_AUTH=${NEO4J_AUTH:-neo4j/neo4jadmin}"
            - "NEO4J_dbms_allow__upgrade=true"
            - 'NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*'
            - 'NEO4J_dbms_security_procedures_whitelist=apoc.*,algo.*'
            - 'NEO4J_apoc_import_file_enabled=true'
            - 'NEO4J_dbms_shell_enabled=true'
            - 'NEO4JLABS_PLUGINS=["apoc"]'
