name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: talosiot-will/nbdevCI@master
      with:
          nbdev_test_cmd: "nbdev_test_nbs --n_workers 1"

